apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-net-discovery.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-net-discovery.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ tpl (.Values.config | toYaml) . | nindent 4 }}
