{{- if .Values.prometheus.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-net-discovery.fullname" . }}
  namespace: {{ .Values.prometheus.monitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "prometheus-net-discovery.labels" . | nindent 4 }}
    {{- if .Values.prometheus.monitor.labels }}
    {{- toYaml .Values.prometheus.monitor.labels | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ default "app.kubernetes.io/name" .Values.prometheus.monitor.jobLabel }}
  endpoints:
  - path: /metrics
    interval: {{ .Values.prometheus.monitor.scrapeInterval }}
    port: http
    scheme: http
    {{- if .Values.prometheus.monitor.honorLabels }}
    honorLabels: true
    {{- end }}
    {{- if .Values.prometheus.monitor.relabelings }}
    relabelings: {{ toYaml .Values.prometheus.monitor.relabelings | nindent 6 }}
    {{- end }}
    {{- if .Values.prometheus.monitor.metricRelabelings }}
    metricRelabelings: {{ toYaml .Values.prometheus.monitor.metricRelabelings | nindent 6 }}
    {{- end }}
  {{- if .Values.prometheus.monitor.namespaceSelector }}
  namespaceSelector: {{ toYaml .Values.prometheus.monitor.namespaceSelector | nindent 4 }}
  {{- else }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prometheus-net-discovery.selectorLabels" . | nindent 6 }}
{{- end }}