{
 "title": "Prometheus Net Discovery",
 "description": "Grafana dashboard for prometheus net discovery application",
 "tags": [
  "discovery",
  "network"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "statistic_interval", "label": "Last detect interval", "query": "1d,3d,1w,2w,3w,4w" },
   { "name": "lost_interval", "label": "Lost Mark", "query": "12h,1d,2d,3d" },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(net_discovery_discovery_running,instance_id)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(net_discovery_discovery_running{instance_id=~\"$instance_id\"},instance)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(net_discovery_discovery_running{instance_id=~\"$instance_id\", instance=~\"$instance\"},network)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "query_result(last_over_time(group by(host)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\"})[$statistic_interval]))"
    }
   },
   {
    "name": "protocol",
    "query": {
     "query": "query_result(last_over_time(group by(protocol)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\"})[$statistic_interval]))"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "query_result(last_over_time(group by(port)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\"})[$statistic_interval]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Networks",
   "type": "stat",
   "description": "Count of networks",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by(instance_id,network)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "piechart",
   "description": "Count of hosts",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(network)(group by(instance_id,network,host)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "piechart",
   "description": "Duration time of last discovery",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(network)(net_discovery_collection_duration_last{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "piechart",
   "description": "Statistic of ports discovery",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(protocol,port,srv)(group by(instance_id,network,host,protocol,port,srv)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"}))",
     "legendFormat": "{{protocol}} / {{port}} / {{srv}}"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "piechart",
   "description": "Statistic of protocols discovery",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(protocol)(group by(instance_id,network,host,protocol,port,srv)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts Total",
   "type": "stat",
   "description": "Count of hosts",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by(instance_id,network,host)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovery State",
   "type": "timeseries",
   "description": "State of discovery network process",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(instance_id,network)(net_discovery_discovery_running{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\"})",
     "legendFormat": "{{instance_id}} / {{network}}"
    }
   ]
  },
  {
   "title": "Discovery Duration",
   "type": "timeseries",
   "description": "Duration time of last discovery process",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance_id,network)(net_discovery_collection_duration_last{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\"})",
     "legendFormat": "{{instance_id}} / {{network}}"
    }
   ]
  },
  {
   "title": "Discovered Hosts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count by(instance_id,network)(group by(instance_id,network,host)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"}))",
     "legendFormat": "{{instance_id}} / {{network}}"
    }
   ]
  },
  {
   "title": "Discovered Hosts and Ports",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "count by(instance_id,network,protocol,port)(group by(instance_id,network,host,protocol,port)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"}))",
     "legendFormat": "{{instance_id}} / {{network}} / {{protocol}} / {{port}}"
    }
   ]
  },
  { "title": "Networks Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Discovered Hosts ($statistic_interval statistic)",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "last_over_time(group by(instance_id,network,host)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"})[${statistic_interval}])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(sum by(instance_id,network)(net_discovery_collection_duration_last{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\"})[${statistic_interval}])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(group by(instance_id,network,host)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"})[${lost_interval}])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Hosts ($statistic_interval statistic)",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "last_over_time(group by(instance_id,network,host,protocol,port,srv)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"})[${statistic_interval}])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(sum by(instance_id,network)(net_discovery_collection_duration_last{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\"})[${statistic_interval}])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(group by(instance_id,network,host,protocol,port,srv)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"})[${lost_interval}])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Hosts and Ports Detail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "state" } },
   "targets": [
    {
     "expr": "last_over_time(group by(instance_id,network,host,protocol,port,srv)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"})[${lost_interval}])\nor\nlast_over_time(group by(instance_id,network,host,protocol,port,srv)(net_discovery_discovered_host{instance_id=~\"$instance_id\",instance=~\"$instance\",network=~\"$network\",host=~\"$host\",protocol=~\"$protocol\",port=~\"$port\"})[${statistic_interval}]) * vector(0)",
     "legendFormat": "{{instance_id}} / {{network}} / {{host}} / {{protocol}} / {{port}} / {{srv}}"
    }
   ]
  }
 ]
}