name: Build Docker Image
on:
  push:
    branches:
      - main
      - add-appication-code

env:
  DOCKEFILE_NAME: Dockerfile
  DOCKER_REPOSITORY: londinzer/prometheus-net-discovery

jobs:
    build:
      name: docker image push
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USER}}
            password: ${{secrets.DOCKERHUB_TOKEN}}
          run: |
            echo $DOCKERHUB_TOKEN | docker login docker.io -u $USERNAME --password-stdin
        - name: build
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f ${DOCKEFILE_NAME} -t ${DOCKER_REPOSITORY}:latest
        - name: push
          id: push-docker-image
          run: docker push ${DOCKER_REPOSITORY}:latest